# Generated by Django 4.1.2 on 2023-03-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_vendorregister_vendor_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name=' Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('message', models.TextField()),
            ],
        ),
    ]
