# Generated by Django 4.1.2 on 2023-03-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField()),
                ('contact_number', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('productImage1', models.ImageField(upload_to='product')),
                ('productImage2', models.ImageField(upload_to='product')),
                ('productImage3', models.ImageField(upload_to='product')),
                ('productImage4', models.ImageField(upload_to='product')),
            ],
        ),
    ]
