# Generated by Django 4.1.2 on 2023-03-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0014_alter_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
