# Generated by Django 4.1.2 on 2023-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0015_remove_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
