# Generated by Django 4.1.1 on 2023-04-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0017_pymentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pymentdetails',
        ),
    ]
