# Generated by Django 4.1.1 on 2023-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0020_delete_pymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='pymentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userid', models.CharField(max_length=50)),
                ('vendorid', models.CharField(max_length=50)),
                ('hotelid', models.CharField(max_length=50)),
                ('noofperson', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('hotel_name', models.CharField(max_length=50)),
                ('PaymentVia', models.CharField(max_length=50)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
                ('transactionId', models.TextField(default=None)),
                ('cheackin', models.DateField()),
                ('cheackout', models.DateField()),
            ],
        ),
    ]
