# Generated by Django 5.0 on 2024-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0021_pymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ac',
            field=models.BooleanField(default=False),
        ),
    ]
